In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import matplotlib.pyplot as plt
import numpy as np


In [3]:
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size
S = 30      # Target sequence length of longest target in batch
S_min = 10  # Minimum target length, for demonstration purposes

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

# Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)

print(input_lengths)


target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long) 

ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()

tensor([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])


In [4]:
def loadnpyfiles(npyname, rootpath=''):
    npzimg = np.load(rootpath+'kothaddekha_ImageArray_'+npyname+'.npy')
    npzlbl = np.load(rootpath+'kothaddekha_LabelArray_' +
                     npyname+'.npy', allow_pickle=True)
    npzlen = np.load(rootpath+'kothaddekha_LenthArray_'+npyname+'.npy')
    return npzimg, npzlbl, npzlen

In [5]:
path = '2k2sec'
rpath = 'data/numpy_arrays/22_class_fc/'


old_imarr, old_lbl, old_lbl_len =  loadnpyfiles(path, rpath)

path = '2k2sec'
rpath = 'data/numpy_arrays/22_class_43_fixed_nosep/'

new_imarr, new_lbl, new_lbl_len =  loadnpyfiles(path, rpath)


In [9]:
print(old_lbl[1])
print(old_lbl_len[1])
print(new_lbl[1])
print(new_lbl_len[1])

print('\n\n')

print(old_imarr[1])
print('\n\n')
print(new_imarr[1])




[18, 1, 5, 18, 9, 1, 13, 3, 7, 3, 16, 4, 12, 7, 5, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
16
[19  2  6 19 10  2 14  4  1  8  4 17  5 13  8  6 17  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
17



[[[255 254 255]
  [255 254 255]
  [254 255 255]
  ...
  [255 254 255]
  [255 255 253]
  [255 255 255]]

 [[251 255 251]
  [251 255 255]
  [ 41 114 146]
  ...
  [ 48  93 148]
  [245 255 255]
  [255 255 255]]

 [[255 254 253]
  [255 255 253]
  [ 46 107 138]
  ...
  [ 41 122 143]
  [240 255 255]
  [255 255 255]]

 ...

 [[255 253 255]
  [255 252 251]
  [101 199  96]
  ...
  [ 49 182 119]
  [230 255 250]
  [255 255 255]]

 [[255 254 255]
  [250 255 249]
  [ 96 207  89]
  ...
  [ 47 191 129]
  [225 255 250]
  [255 255 255]]

 [[252 255 251]
  [255 252 255]
  [255 255 251]
  ...
  [255 252 255]
  [255 253 255]
  [255 255 255]]]



[[[255 254 255]
  [255 254 255]
  [254 255 255]
  ...
  [255 254 255]
  [255 255 253]
  [255 